### ISSUE TITLE
how can I navigation one page to another

### ISSUE THREAD

**Issue by MehediHasannOvi** [resfandiari/flutter_side_menu#1]
can't navigation to one page to another, when I use SideMenuItemDataTile ontap Function full screen are change how can I change only body part

**Comment by resfandiari** [comment]
> can't navigation to one page to another, when I use SideMenuItemDataTile ontap Function full screen are change how can I change only body part

The project now includes simple and go router examples. Please take a look at them.

[simple](https://github.com/resfandiari/flutter_side_menu/blob/main/example/lib/simple.dart)
[go_router](https://github.com/resfandiari/flutter_side_menu/blob/main/example/lib/go_router.dart)
