### ISSUE TITLE
Package conflict with last flutter version : Badge.dart

### ISSUE THREAD

**Issue by vd3d** [resfandiari/flutter_side_menu#3]
Hi,

I got a package conflict, here is the message I got:

error G50A53C35: 'Badge' is imported from both 'package:badges/src/badge.dart' and 'package:flutter/src/material/badge.dart'

Do you have any fix for this?

**Comment by resfandiari** [comment]
Hi @vd3d , Sorry about that, it will be fixed as soon as possible.
