### ISSUE TITLE
"titleStyle" cant change text color

### ISSUE THREAD

**Issue by NeonX** [resfandiari/flutter_side_menu#8]
I try to change text color to  Colors.amber but it's still black.

SideMenuItemDataTile(
    isSelected: _currentIndex == 3,
    onTap: () => setState(() => _currentIndex = 3),
    title: 'Demo',
    icon: const Icon(Icons.car_crash),
    titleStyle: GoogleFonts.notoSansThai(
                    textStyle: const TextStyle(
                    fontSize: 14,
                    color: Colors.amber,
                  ),
                ),
  ),

**Comment by resfandiari** [comment]
Have you tried "selectedTitleStyle"?

**Comment by angela-boyadjian** [comment]
I have the same problem ! It seems to only be the color, if I add a text decoration such as an underline it works fine but the color doesn't change.
